CREATE DATABASE bd_alejandro_escobar_clan8;

CREATE TABLE rm_cities (
	city_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	city_name varchar(100) NOT NULL
);

CREATE TABLE rm_categories (
	category_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	category_name varchar(100) NOT NULL
);

CREATE TABLE rm_products (
  product_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY, 
  product_sku varchar(50) NOT NULL UNIQUE,
  product_name varchar(150) NOT NULL,
  product_desc varchar(255),
  unit_measure varchar(30) NOT NULL,
  unit_price decimal(12, 2) NOT NULL CHECK (unit_price >= 0),
  
  category_id int NOT NULL,

  CONSTRAINT fk_products_categories
  	FOREIGN KEY (category_id)
	REFERENCES rm_categories (category_id)
	ON DELETE RESTRICT
);

CREATE TABLE rm_suppliers (
  supplier_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY, 
  supplier_tax_id varchar(50) NOT NULL UNIQUE,
  supplier_name varchar(150) NOT NULL,
  supplier_phone varchar(30),

  city_id int NOT NULL,

  CONSTRAINT fk_suppliers_cities
  	FOREIGN KEY (city_id)
	REFERENCES rm_cities (city_id)
	ON DELETE RESTRICT
);

CREATE TABLE rm_warehouses (
  warehouse_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  warehouse_code varchar(20) UNIQUE NOT NULL,
  warehouse_name varchar(150) NOT NULL,
  warehouse_address varchar(200) NOT NULL,

  city_id int NOT NULL,
  
  CONSTRAINT fk_warehouses_cities
  	FOREIGN KEY (city_id)
	REFERENCES rm_cities (city_id)
	ON DELETE RESTRICT
);


CREATE TABLE rm_purchases (
  purchase_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  purchase_code varchar(20) UNIQUE NOT NULL,
  purchase_date timestamp NOT NULL,
  purchase_quantity int NOT NULL CHECK (purchase_quantity > 0),
  
  supplier_id int NOT NULL,
  warehouse_id int NOT NULL,
  product_id int NOT NULL,

  CONSTRAINT fk_purchases_warehouses
	FOREIGN KEY (warehouse_id)
	REFERENCES rm_warehouses (warehouse_id)
	ON DELETE RESTRICT,

  CONSTRAINT fk_purchases_products
	FOREIGN KEY (product_id)
	REFERENCES rm_products (product_id)
	ON DELETE RESTRICT,
	
  CONSTRAINT fk_purchases_suppliers
	FOREIGN KEY (supplier_id)
	REFERENCES rm_suppliers (supplier_id)
	ON DELETE RESTRICT
);


CREATE TABLE rm_employees (
	employee_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	employee_name varchar(150) NOT NULL
);


CREATE TABLE rm_inventory_movements (
  movement_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  movement_code varchar(20) UNIQUE NOT NULL,
  movement_type varchar(30) NOT NULL CHECK (movement_type IN ('IN','OUT')),
  movement_date timestamp NOT NULL,
  movement_quantity int NOT NULL  CHECK (movement_quantity > 0),
  stock_after_movement int NOT NULL  CHECK (stock_after_movement > 0),
  
  warehouse_id int NOT NULL,
  product_id int NOT NULL,
  employee_id int NOT NULL,
  purchase_id int,

  CONSTRAINT fk_inventory_movements_warehouses
	FOREIGN KEY (warehouse_id)
	REFERENCES rm_warehouses (warehouse_id)
	ON DELETE RESTRICT,

  CONSTRAINT fk_inventory_movements_products
	FOREIGN KEY (product_id)
	REFERENCES rm_products (product_id)
	ON DELETE RESTRICT,

  CONSTRAINT fk_inventory_movements_employees
	FOREIGN KEY (employee_id)
	REFERENCES rm_employees (employee_id)
	ON DELETE RESTRICT,

  CONSTRAINT fk_inventory_movements_purchases
	FOREIGN KEY (purchase_id)
	REFERENCES rm_purchases (purchase_id)
	ON DELETE RESTRICT
);

CREATE INDEX idx_purchases_product ON rm_purchases(product_id);
CREATE INDEX idx_purchases_supplier ON rm_purchases(supplier_id);
CREATE INDEX idx_movements_warehouse ON rm_inventory_movements(warehouse_id);
CREATE INDEX idx_movements_product ON rm_inventory_movements(product_id);

COPY rm_cities(city_name)
FROM 'C:\Users\Aleja\developer\SQL\simulacro\archivos_csv\rm_cities.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM rm_cities;
